services:
  db:
    container_name: rssreader_db
    image: postgres:15
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    restart: "on-failure"
    ports:
      - 5432:5432
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - .env
  testdb:
    container_name: rssreader_testdb
    image: postgres:15
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    restart: "on-failure"
    ports:
      - 5433:5432
    env_file:
      - .env
